---
- name: Backup Docker volumes
  hosts: localhost
  vars:
    config_file: "{{ playbook_dir }}/config.yml"

  # Override config from command line with `ansible-playbook backup-volumes.yml -e @/path/to/config.yml`
  vars_files:
    - "{{ config_file }}"

  tasks:
    - name: Fail if target_service is not defined in services
      fail:
        msg: "Service '{{ target_service }}' not found in config.yml"
      when: target_service is defined and target_service not in services

    - name: Backup volumes for desired services
      include_tasks: "{{ service_task }}"
      loop: "{{ services | dict2items if target_service is not defined else services | dict2items | selectattr('key', 'equalto', target_service) }}"
      vars:
        service: "{{ item.key }}"
        compose: "{{ item.value.compose }}"
        stop_containers: "{{ item.value.stop_containers }}"
        backups_kept: "{{ item.value.backups_kept }}"
        volumes: "{{ item.value.volumes | default([]) }}"
        backup_location: "{{ backup_root }}/{{ item.key }}"
        operation_name: "Backup"
        operation_task: "{{ backup_task }}"
